---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

### Avoiding R bottlenecks with Rcpp

I will introduce the Rcpp package for streamlining R code with C++ functions
to avoid some common computational bottlenecks when writing R functions in a
manner that's easy to use with minimal C++ knowledge. During the presentation,
I will provide an example of developing a package with compiled code and
demonstrate the "workflowr" package for organizing your projects into a
version controlled website for documenting your results.

This document is broken into three main sections: 

1. [Brief introduction to Rcpp](intro.html)
1. [Building a package](packages.html)
1. [Case study: Skew Normal Mixture distributions](sn_mix.html)

## Using workflowr
This document was created using <tt>workflowr</tt>. WorkflowR is an R package
that allows for an effective and reproducible way to share organize your projects
and share your results with collaborators and advisors. The benefit of <tt>workflowr</tt>
is that it allows you to build an organized project template with analyses in
<tt>Rmarkdown</tt>, use git to version control and push to github or gitlab, and
publish your results to a website with only a handful of function calls within R.

The main functions you need are:

1. <tt>wflow_start()</tt> -- Start a new project
1. <tt>wflow_build()</tt> -- Render Rmarkdown and display html
1. <tt>wflow_status()</tt> -- show status of project/files needed to be committed
1. <tt>wflow_publish()</tt> -- deploy website, commit to github/gitlab
1. <tt>wflow_git_push()</tt> -- push changes

Other useful functions are:

* <tt>wflow_git_commit()</tt> (commit without publishing)
* <tt>wflow_git_pull()</tt>
* <tt>wflow_git_config()</tt>

When deploying your website to the internet, note that github pages doesn't allow
for private sites. If privacy is a large concern in your research, consider using
gitlab instead.

Learn more here: https://jdblischak.github.io/workflowr/
