---
title: "Rcpp in Packages"
Author: "Stephen Cristiano"
output:
  workflowr::wflow_html:
    toc: true
editor_options:
  chunk_output_type: console
---


## Anatomy of an R Package

Inspection of R source code for any R package will reveal the following
directories and files:

* R: for R functions
* vignettes: Latex papers weaving R code and indicating the intended workflow
  of an analysis
* man: documentation for exported R functions
* src: compiled code
* DESCRIPTION: file provides a brief description of the project, a version
  number, and any packages for which your package depends.

# Using Rcpp:

* All compiled code goes in package/src directory
* Code in src/ will be automatically compiled and shared
  libraries created when building the package.
* Instantiate an Rcpp package: Rcpp.package.skeleton

## devtools

* <tt>devtools::use_rcpp()</tt> to set your package up with Rcpp. This will
  * create a src/ directory for your compiled code
  * Add Rcpp to the LinkingTo and Imports fields in the DESCRIPTION.
  * Set up your .gitignore to ignore compiled output files
  * Give you roxygen flags to add to your package

roxygen can be used to add documentation to your C++ written functions in the
usual with, but with <tt>//'</tt> instead of <tt>#'</tt>.

## Exporting/importing C++ code
Use header (.h) files to make your C++ functions callable elsewhere.
